on: push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: check environment
      run: env
    - name: Hello world action step
      id: hello
      uses: jinyyo/GA-TEST@master
      with:
        who-to-greet: 'Mona the Octocat'

